//! Launcher layer: resume-command generation for the target tools and the
//! post-migration one-click open actions.
//!
//! The resume-command helpers currently support Codex and Claude Code. The
//! one-click open actions (`open_in_terminal` / `open_zcode_app`) are
//! implemented per platform (macOS / Linux / Windows) and must only be
//! invoked by the UI when the user clicks a button. The tests in this module
//! only verify argument construction; nothing is ever actually launched.

/// Codex resume command delivered after a successful migration.
///
/// `cd '<project_dir>' && codex resume <session_id>`
///
/// Security (code-review fix): project_dir comes from the `cwd` field of the
/// source session file (externally controllable text), and this command gets
/// pasted by the user into a terminal, so it must never be concatenated in
/// raw. See [`cd_prefix`] for the quoting rules.
pub fn codex_resume_command(session_id: &str, project_dir: &str) -> String {
    format!("{}codex resume {session_id}", cd_prefix(project_dir))
}

/// Claude Code resume command delivered after a successful migration.
///
/// `cd '<project_dir>' && claude --resume <session_id>`
///
/// Quoting rules are identical to [`codex_resume_command`] (both share
/// [`cd_prefix`]).
pub fn claude_resume_command(session_id: &str, project_dir: &str) -> String {
    format!("{}claude --resume {session_id}", cd_prefix(project_dir))
}

/// Shared `cd` segment for both resume commands: when the path contains no
/// single quote it is wrapped in single quotes (no expansion of any kind
/// happens inside shell single quotes); when it is empty or contains a
/// single quote the cd segment is dropped entirely (session_id is a uuid v4
/// generated by this tool and is safe by construction).
fn cd_prefix(project_dir: &str) -> String {
    if project_dir.is_empty() || project_dir.contains('\'') {
        String::new()
    } else {
        format!("cd '{project_dir}' && ")
    }
}

// ---------- One-click open (the actual launch happens only when the user
// clicks a button in the UI) ----------

/// Launches `command` in a new terminal window.
///
/// Platform behavior:
/// - macOS: `osascript` tells Terminal.app to run the command in a new
///   window and brings Terminal to the front.
/// - Linux: the first terminal emulator found on `PATH` (by preference)
///   runs `sh -c <command>` via the emulator's `-e` form; the emulator is
///   spawned without waiting. Returns `Unsupported` when none of the known
///   emulators is installed.
/// - Windows: `cmd /C start cmd /K "<command>"` opens a fresh console
///   window that stays open after the command finishes.
///
/// Pure helpers for each platform are compiled on every host (guarded with
/// `allow(dead_code)` where needed) so their unit tests run everywhere.
pub fn open_in_terminal(command: &str) -> std::io::Result<()> {
    #[cfg(target_os = "macos")]
    {
        open_in_terminal_macos(command)
    }
    #[cfg(target_os = "windows")]
    {
        open_in_terminal_windows(command)
    }
    #[cfg(all(unix, not(target_os = "macos")))]
    {
        open_in_terminal_linux(command)
    }
}

/// Opens the ZCode desktop app.
///
/// - macOS: `open -a ZCode` launches by application name; when the app is
///   missing, `open` itself fails and the error is passed through.
/// - Windows: probes the common `ZCode.exe` install locations and spawns
///   the first hit; returns an error with guidance when none exists.
/// - Linux: no official ZCode desktop build exists, so a `zcode` executable
///   on `PATH` is tried and otherwise an explanatory error is returned.
pub fn open_zcode_app() -> std::io::Result<()> {
    #[cfg(target_os = "macos")]
    {
        open_zcode_app_macos()
    }
    #[cfg(target_os = "windows")]
    {
        open_zcode_app_windows()
    }
    #[cfg(all(unix, not(target_os = "macos")))]
    {
        open_zcode_app_linux()
    }
}

// ---------- macOS ----------

/// macOS: runs the AppleScript pair built by [`osascript_args_for_terminal`].
/// osascript exits as soon as the command has been handed to Terminal, so
/// waiting for it does not block on the launched program while still
/// surfacing failures (e.g. a broken script).
#[cfg(target_os = "macos")]
fn open_in_terminal_macos(command: &str) -> std::io::Result<()> {
    let mut script = std::process::Command::new("osascript");
    script.args(osascript_args_for_terminal(command));
    run_and_check(&mut script, "osascript")
}

/// macOS: `open -a ZCode` launches by application name; when the app cannot
/// be found, `open` itself reports the error and it is passed through.
#[cfg(target_os = "macos")]
fn open_zcode_app_macos() -> std::io::Result<()> {
    let mut open = std::process::Command::new("open");
    open.args(open_app_args("ZCode"));
    run_and_check(&mut open, "open")
}

/// Builds the osascript arguments that make Terminal run `command` (pure
/// function, unit-testable).
///
/// Two AppleScript statements: `do script` executes the command in a new
/// Terminal window via a shell, and `activate` brings Terminal to the
/// front. The command reaches osascript through the argument array (no
/// shell involved, so it is never re-interpreted); only the AppleScript
/// string layer needs escaping, see [`escape_applescript_string`].
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
fn osascript_args_for_terminal(command: &str) -> Vec<String> {
    vec![
        "-e".to_string(),
        format!(
            "tell application \"Terminal\" to do script \"{}\"",
            escape_applescript_string(command)
        ),
        "-e".to_string(),
        "tell application \"Terminal\" to activate".to_string(),
    ]
}

/// Builds the arguments for `open -a <app name>` (pure function, testable).
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
fn open_app_args(app_name: &str) -> Vec<String> {
    vec!["-a".to_string(), app_name.to_string()]
}

/// Escapes an AppleScript string literal: backslashes and double quotes get
/// a backslash prefix. Every other character (single quotes, newlines,
/// non-ASCII) passes through literally inside an AppleScript string.
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
fn escape_applescript_string(text: &str) -> String {
    let mut escaped = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            _ => escaped.push(ch),
        }
    }
    escaped
}

// ---------- Linux ----------

/// Terminal emulators probed in order of preference (pure data, testable).
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
const LINUX_TERMINAL_CANDIDATES: [&str; 5] =
    ["gnome-terminal", "konsole", "kitty", "alacritty", "xterm"];

/// Linux: spawns `sh -c <command>` inside the first known terminal emulator.
/// The emulator is spawned (not waited for) because most terminals stay in
/// the foreground for as long as their window is open.
#[cfg(all(unix, not(target_os = "macos")))]
fn open_in_terminal_linux(command: &str) -> std::io::Result<()> {
    let path = std::env::var_os("PATH");
    let terminal = LINUX_TERMINAL_CANDIDATES
        .iter()
        .find_map(|name| find_executable_in_path(name, path.as_deref()))
        .ok_or_else(|| {
            unsupported_error(
                "未找到已知的终端模拟器(gnome-terminal/konsole/kitty/alacritty/xterm),\
                 请安装其中之一,或手动复制命令到终端执行",
            )
        })?;
    let mut emulator = std::process::Command::new(terminal);
    emulator.args(linux_terminal_args(command));
    emulator.spawn().map(|_| ())
}

/// Linux: no official ZCode desktop build exists (macOS / Windows only); a
/// `zcode` executable on `PATH` is tried (e.g. a user wrapper script) and
/// otherwise an explanatory error is returned.
#[cfg(all(unix, not(target_os = "macos")))]
fn open_zcode_app_linux() -> std::io::Result<()> {
    match find_executable_in_path("zcode", std::env::var_os("PATH").as_deref()) {
        Some(zcode) => std::process::Command::new(zcode).spawn().map(|_| ()),
        None => Err(unsupported_error(
            "Linux 暂无官方 ZCode 桌面版(仅 macOS / Windows);若已安装兼容版本,请手动启动",
        )),
    }
}

/// Linux terminal argument profile: run `sh -c <command>` inside the
/// emulator, so the shell handles `cd ... && ...` chains. Every emulator in
/// [`LINUX_TERMINAL_CANDIDATES`] accepts the `-e <program> [args...]` form.
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
fn linux_terminal_args(command: &str) -> Vec<String> {
    ["-e", "sh", "-c", command]
        .iter()
        .map(|arg| arg.to_string())
        .collect()
}

/// Looks up `name` in a PATH-style value and returns the first entry where
/// `name` exists, is a regular file, and has an executable bit. Unix-only:
/// it relies on the permission bit model.
// Used by the Linux code paths; also compiled on macOS so its unit tests
// (which build a fake PATH) run there.
#[cfg(unix)]
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn find_executable_in_path(
    name: &str,
    path_value: Option<&std::ffi::OsStr>,
) -> Option<std::path::PathBuf> {
    use std::os::unix::fs::PermissionsExt;

    let path_value = path_value?;
    for dir in std::env::split_paths(path_value) {
        let candidate = dir.join(name);
        let Ok(metadata) = std::fs::metadata(&candidate) else {
            continue;
        };
        if !metadata.is_file() {
            continue;
        }
        if metadata.permissions().mode() & 0o111 != 0 {
            return Some(candidate);
        }
    }
    None
}

// ---------- Windows ----------

/// Windows: `cmd /C start cmd /K "<command>"`. The outer cmd returns as
/// soon as `start` has launched the new console, so waiting for it (to
/// capture a possible error) is fine. CREATE_NO_WINDOW hides the flash of
/// the intermediate console; `start` still gives the inner cmd its own
/// visible window.
#[cfg(target_os = "windows")]
fn open_in_terminal_windows(command: &str) -> std::io::Result<()> {
    use std::os::windows::process::CommandExt;

    const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    let mut shell = std::process::Command::new("cmd");
    shell.arg("/C").arg("start").arg("cmd").arg("/K");
    // raw_arg: the quoting done by windows_terminal_command_arg is final;
    // the Rust runtime must not add a second quoting layer on top.
    shell.raw_arg(windows_terminal_command_arg(command));
    shell.creation_flags(CREATE_NO_WINDOW);
    run_and_check(&mut shell, "cmd")
}

/// Windows: probes the common ZCode.exe install locations and spawns the
/// first hit (GUI app: spawn without waiting). Returns an error with
/// guidance when none of them exists.
#[cfg(target_os = "windows")]
fn open_zcode_app_windows() -> std::io::Result<()> {
    let candidates = zcode_windows_candidates(
        std::env::var_os("LOCALAPPDATA")
            .map(std::path::PathBuf::from)
            .as_deref(),
        std::env::var_os("ProgramFiles")
            .map(std::path::PathBuf::from)
            .as_deref(),
        std::env::var_os("ProgramFiles(x86)")
            .map(std::path::PathBuf::from)
            .as_deref(),
    );
    for exe in &candidates {
        if exe.is_file() {
            return std::process::Command::new(exe).spawn().map(|_| ());
        }
    }
    Err(unsupported_error(
        "未找到 ZCode.exe(已在 %LOCALAPPDATA%\\Programs\\ZCode 与 %ProgramFiles%\\ZCode\
         等常见位置探测);请手动启动 ZCode 应用",
    ))
}

/// Wraps `command` as a single quoted cmd argument (pure function,
/// testable): the whole command is passed as one argument, wrapped in double
/// quotes, with internal double quotes escaped as `\"`, so the inner
/// `cmd /K` receives it verbatim.
///
/// Resume commands generated by this crate contain single-quoted paths and
/// plain uuids (never double quotes); the escaping is defensive only.
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
fn windows_terminal_command_arg(command: &str) -> String {
    format!("\"{}\"", command.replace('"', "\\\""))
}

/// Candidate `ZCode.exe` locations to probe (pure function, testable):
/// per-user install first (`%LOCALAPPDATA%\Programs\ZCode`), then per-
/// machine installs under `%ProgramFiles%` / `%ProgramFiles(x86)%`.
// Compiled on every platform so its unit tests run on every host.
#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
fn zcode_windows_candidates(
    local_appdata: Option<&std::path::Path>,
    program_files: Option<&std::path::Path>,
    program_files_x86: Option<&std::path::Path>,
) -> Vec<std::path::PathBuf> {
    let mut candidates = Vec::new();
    if let Some(base) = local_appdata {
        candidates.push(base.join("Programs").join("ZCode").join("ZCode.exe"));
    }
    for base in [program_files, program_files_x86].into_iter().flatten() {
        candidates.push(base.join("ZCode").join("ZCode.exe"));
    }
    candidates
}

// ---------- Shared helpers ----------

/// `Unsupported` io error carrying a user-facing message.
// Only the Linux / Windows paths use it; unused on macOS outside tests.
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn unsupported_error(message: &str) -> std::io::Error {
    std::io::Error::new(std::io::ErrorKind::Unsupported, message)
}

/// Runs an external command to completion and checks the result: on a
/// non-zero exit the code and stderr are folded into the returned error.
///
/// The commands passed here (osascript / open / cmd) only initiate an
/// action and exit right away, so waiting for them does not hang on the
/// launched program while still yielding the failure reason (e.g. the
/// application does not exist).
// Used by the macOS and Windows paths; unused on Linux.
#[cfg_attr(all(unix, not(target_os = "macos")), allow(dead_code))]
fn run_and_check(command: &mut std::process::Command, label: &str) -> std::io::Result<()> {
    let output = command.output()?;
    if output.status.success() {
        return Ok(());
    }
    let status = match output.status.code() {
        Some(code) => format!("退出码 {code}"),
        None => "被信号终止".to_string(),
    };
    let stderr = String::from_utf8_lossy(&output.stderr);
    let detail = stderr.trim();
    Err(std::io::Error::other(format!(
        "`{label}` 执行失败({status}):{detail}"
    )))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------- TC-LAUNCH-01 ----------
    #[test]
    fn tc_launch_01_resume_command_format() {
        assert_eq!(
            codex_resume_command("8a0d022a-6659-4097-bb6b-cff0fd6e7ed1", "/Users/x/proj"),
            "cd '/Users/x/proj' && codex resume 8a0d022a-6659-4097-bb6b-cff0fd6e7ed1"
        );
    }

    /// Injection guard (code-review addition): a project_dir containing a
    /// single quote drops the cd segment; metacharacters like `$` / `;` /
    /// backticks inside the single-quoted path lose their shell meaning.
    #[test]
    fn tc_launch_02_quoting_blocks_injection() {
        assert_eq!(
            codex_resume_command("8a0d022a-6659-4097-bb6b-cff0fd6e7ed1", "/tmp/x'; rm -rf ~"),
            "codex resume 8a0d022a-6659-4097-bb6b-cff0fd6e7ed1"
        );
        // Regular metacharacters stay literal inside single quotes
        assert_eq!(
            codex_resume_command("sid", "/tmp/a;b&c$d`e"),
            "cd '/tmp/a;b&c$d`e' && codex resume sid"
        );
        // Empty path: resume command only
        assert_eq!(codex_resume_command("sid", ""), "codex resume sid");
    }

    // ---------- TC-LAUNCH-03 ----------
    #[test]
    fn tc_launch_03_claude_resume_command_format() {
        assert_eq!(
            claude_resume_command("8a0d022a-6659-4097-bb6b-cff0fd6e7ed1", "/Users/x/proj"),
            "cd '/Users/x/proj' && claude --resume 8a0d022a-6659-4097-bb6b-cff0fd6e7ed1"
        );
        // Same quoting guard as the codex variant: single quote drops cd
        assert_eq!(
            claude_resume_command("8a0d022a-6659-4097-bb6b-cff0fd6e7ed1", "/tmp/x'; rm -rf ~"),
            "claude --resume 8a0d022a-6659-4097-bb6b-cff0fd6e7ed1"
        );
        // Regular metacharacters stay literal inside single quotes
        assert_eq!(
            claude_resume_command("sid", "/tmp/a;b&c$d`e"),
            "cd '/tmp/a;b&c$d`e' && claude --resume sid"
        );
        // Empty path: resume command only
        assert_eq!(claude_resume_command("sid", ""), "claude --resume sid");
    }

    // ---------- TC-LAUNCH-04: osascript argument construction ----------
    // Structure: the do script statement carries the command, the activate
    // statement brings Terminal to the front. Argument construction only —
    // never actually opens Terminal (tests must not pop windows).
    #[test]
    fn tc_launch_04_terminal_osascript_args() {
        let args = osascript_args_for_terminal("cd '/Users/x/proj' && codex resume abc");
        assert_eq!(args.len(), 4);
        assert_eq!(args[0], "-e");
        assert_eq!(
            args[1],
            "tell application \"Terminal\" to do script \"cd '/Users/x/proj' && codex resume abc\""
        );
        assert_eq!(args[2], "-e");
        assert_eq!(args[3], "tell application \"Terminal\" to activate");
    }

    // TC-LAUNCH-05: AppleScript string escaping — double quotes and
    // backslashes in the command must be escaped, otherwise the string
    // would truncate at the quote / the backslash would be eaten by
    // AppleScript; everything else passes through untouched.
    #[test]
    fn tc_launch_05_applescript_escaping() {
        assert_eq!(escape_applescript_string("plain text"), "plain text");
        assert_eq!(escape_applescript_string("echo \"hi\""), "echo \\\"hi\\\"");
        assert_eq!(escape_applescript_string("a\\b"), "a\\\\b");
        // Non-ASCII and single quotes pass through untouched
        assert_eq!(escape_applescript_string("中文'引号'"), "中文'引号'");
        // Combined: the escaped command is still one complete do script string
        let args = osascript_args_for_terminal("echo \"ok\" && cd 'C:\\work'");
        assert_eq!(
            args[1],
            "tell application \"Terminal\" to do script \"echo \\\"ok\\\" && cd 'C:\\\\work'\""
        );
    }

    // TC-LAUNCH-06: `open` argument construction (-a launches by app name).
    #[test]
    fn tc_launch_06_open_app_args() {
        assert_eq!(open_app_args("ZCode"), vec!["-a", "ZCode"]);
    }

    // TC-LAUNCH-07: Linux terminal argument profile — `-e sh -c <command>`
    // hands the command to a shell inside the emulator without any
    // re-quoting (the command travels through the argument array).
    #[test]
    fn tc_launch_07_linux_terminal_args() {
        assert_eq!(
            linux_terminal_args("cd '/home/x' && codex resume abc"),
            vec!["-e", "sh", "-c", "cd '/home/x' && codex resume abc"]
        );
    }

    // TC-LAUNCH-08: Linux terminal emulator preference order.
    #[test]
    fn tc_launch_08_linux_terminal_candidates_order() {
        assert_eq!(
            LINUX_TERMINAL_CANDIDATES,
            ["gnome-terminal", "konsole", "kitty", "alacritty", "xterm"]
        );
    }

    // TC-LAUNCH-09: PATH lookup finds an executable file in any PATH entry
    // and rejects non-executable or missing files. Runs on every unix host
    // (macOS included) via a synthetic PATH; nothing is executed.
    #[cfg(unix)]
    #[test]
    fn tc_launch_09_find_executable_in_path() {
        use std::os::unix::fs::PermissionsExt;

        let empty_dir = tempfile::tempdir().unwrap();
        let tools_dir = tempfile::tempdir().unwrap();
        let executable = tools_dir.path().join("hub-fake-term");
        std::fs::write(&executable, b"#!/bin/sh\n").unwrap();
        std::fs::set_permissions(&executable, std::fs::Permissions::from_mode(0o755)).unwrap();
        let non_executable = tools_dir.path().join("hub-not-executable");
        std::fs::write(&non_executable, b"x").unwrap();

        let path = std::env::join_paths([empty_dir.path(), tools_dir.path()]).unwrap();
        let path = path.as_os_str();
        // Found in the second PATH entry, returned as the full candidate path
        assert_eq!(
            find_executable_in_path("hub-fake-term", Some(path)),
            Some(executable)
        );
        // Exists but not executable, or entirely missing: no hit
        assert_eq!(
            find_executable_in_path("hub-not-executable", Some(path)),
            None
        );
        assert_eq!(find_executable_in_path("hub-missing", Some(path)), None);
        // No PATH value at all: no hit
        assert_eq!(find_executable_in_path("hub-fake-term", None), None);
    }

    // TC-LAUNCH-10: Windows terminal quoting — the whole command becomes one
    // double-quoted argument; internal double quotes are escaped; single
    // quotes (the form our resume commands actually use) pass through.
    #[test]
    fn tc_launch_10_windows_terminal_quoting() {
        assert_eq!(
            windows_terminal_command_arg("cd 'C:\\work' && codex resume abc"),
            "\"cd 'C:\\work' && codex resume abc\""
        );
        assert_eq!(
            windows_terminal_command_arg("echo \"hi\""),
            "\"echo \\\"hi\\\"\""
        );
    }

    // TC-LAUNCH-11: Windows ZCode.exe probe locations — per-user install
    // first, then per-machine Program Files variants; no bases means no
    // candidates. Expected values are built with join() to stay
    // separator-agnostic across test hosts.
    #[test]
    fn tc_launch_11_windows_zcode_candidates() {
        use std::path::Path;

        let local = Path::new("C:/Users/x/AppData/Local");
        let program_files = Path::new("C:/Program Files");
        let program_files_x86 = Path::new("C:/Program Files (x86)");
        let candidates =
            zcode_windows_candidates(Some(local), Some(program_files), Some(program_files_x86));
        assert_eq!(
            candidates,
            vec![
                local.join("Programs").join("ZCode").join("ZCode.exe"),
                program_files.join("ZCode").join("ZCode.exe"),
                program_files_x86.join("ZCode").join("ZCode.exe"),
            ]
        );
        assert!(candidates.iter().all(|path| path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.eq_ignore_ascii_case("zcode.exe"))));
        assert_eq!(
            zcode_windows_candidates(None, Some(program_files), None),
            vec![program_files.join("ZCode").join("ZCode.exe")]
        );
        assert!(zcode_windows_candidates(None, None, None).is_empty());
    }
}
